kind: Service
apiVersion: v1
metadata:
  name: connectionsposts-svc
spec:
  selector:
    app: connections-posts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: connections-posts
  labels:
    app: connections-posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connections-posts
  template:
    metadata:
      labels:
        app: connections-posts
        appcollection: blog-aggregator
    spec:
      containers:
      - name: connections-posts
        image: cdavisafc/cloudnative-eventlog-connectionposts
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook"
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"datasource":{"url":"jdbc:mysql://mysql-svc/cookbookconnectionsposts"}}}'
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafkasvc:9092"
          - name: VERSIONING_TRIGGER
            value: "1"
