kind: Service
apiVersion: v1
metadata:
  name: posts-svc
spec:
  selector:
    app: posts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: posts
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      name: posts
      labels:
        app: posts
        appcollection: blog-aggregator
    spec:
      containers:
      - name: posts
        image: cdavisafc/cloudnative-eventlog-posts:0.0.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONNECTIONSPOSTSCONTROLLER_URL
            value: "http://connectionsposts-svc/posts?userIds="
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"datasource":{"url":"jdbc:mysql://mysql-svc/cookbookposts"}}}'
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook"
          - name: VERSIONING_TRIGGER
            value: "12"
