
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        args: []
        securityContext:
          privileged: true
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_LISTENERS
            value: EXTERNAL://kafkasvc:9092, INTERNAL://localhost:9093
          - name: KAFKA_LISTENERS
            value: EXTERNAL://:9092, INTERNAL://:9093
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: EXTERNAL:PLAINTEXT, INTERNAL:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INTERNAL
#          - name: KAFKA_ADVERTISED_PORT
#            value: "9092"
#          - name: KAFKA_ADVERTISED_HOST_NAME
#            value: 10.106.191.32
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zoo:2181
          - name: KAFKA_BROKER_ID
            value: "0"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
#transaction.state.log.replication.factor=1
#transaction.state.log.min.isr=1
#listeners=INTERNAL://:9092,EXTERNAL://:39092
#advertised.listeners=INTERNAL://10.242.44.55:9092,EXTERNAL://[public_ip]:39092
#listener.security.protocol.map
#inter.broker.listener.name