kind: Service
apiVersion: v1
metadata:
  name: connection-posts-svc
spec:
  selector:
    app: connection-posts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: connection-posts
  labels:
    app: connection-posts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: connection-posts
  template:
    metadata:
      labels:
        app: connection-posts
        appcollection: blog-aggregator
    spec:
      containers:
      - name: connection-posts
        image: cdavisafc/cloudnative-troubleshooting-connectionposts
#        resources:
#          limits:
#            memory: "2048Mi"
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
#          initialDelaySeconds: 60
#          periodSeconds: 5
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"zipkin":{"baseUrl":"http://zipkin-svc:9411/"}}}'
          - name: CONNECTIONPOSTSCONTROLLER_POSTSURL
            value: "http://posts-svc/posts?userIds="
          - name: CONNECTIONPOSTSCONTROLLER_CONNECTIONSURL
            value: "http://connections-svc/connections/"
          - name: CONNECTIONPOSTSCONTROLLER_USERSURL
            value: "http://connections-svc/users/"
          - name: CONNECTIONPOSTSCONTROLLER_IMPLEMENTRETRIES
            value: "true"
          - name: CONNECTIONPOSTSCONTROLLER_CONNECTTIMEOUT
            value: "500"
          - name: CONNECTIONPOSTSCONTROLLER_READTIMEOUT
            value: "500"
          - name: REDIS_HOSTNAME
            value: "redis-svc"
          - name: REDIS_PORT
            value: "6379"
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook-connectionsposts"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://sccs-svc:8888"
          - name: SPRING_SLEUTH_SAMPLER_PERCENTAGE
            value: "0.01"
          - name: SPRING_CLOUD_CONFIG_NAME
            value: "mycookbook"
          - name: VERSIONING_TRIGGER
            value: "14"
