kind: Service
apiVersion: v1
metadata:
  name: connection-posts
spec:
  selector:
    app: connection-posts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: connection-posts
  labels:
    app: connection-posts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connection-posts
  template:
    metadata:
      labels:
        app: connection-posts
    spec:
      containers:
      - name: connection-posts
        image: cdavisafc/cloudnative-applifecycle-connectionposts:0.0.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONNECTIONPOSTSCONTROLLER_POSTSURL
            value: "http://192.168.99.100:31930/posts?userIds="
          - name: CONNECTIONPOSTSCONTROLLER_CONNECTIONSURL
            value: "http://192.168.99.100:30389/connections/"
          - name: CONNECTIONPOSTSCONTROLLER_USERSURL
            value: "http://192.168.99.100:30389/users/"
          - name: REDIS_HOSTNAME
            value: "192.168.99.100"
          - name: REDIS_PORT
            value: "31456"
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://192.168.99.100:32679"
          - name: VERSIONING_TRIGGER
            value: "1"