kind: Service
apiVersion: v1
metadata:
  name: connection-posts
spec:
  selector:
    app: connection-posts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: connection-posts
  labels:
    app: connection-posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connection-posts
  template:
    metadata:
      labels:
        app: connection-posts
    spec:
      containers:
      - name: connection-posts
        image: cdavisafc/cloudnative-statelessness-connectionposts-stateless
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            value: "8080"
          - name: CONNECTIONPOSTSCONTROLLER_POSTSURL
            value: "http://192.168.99.100:31040/posts?userIds="
          - name: CONNECTIONPOSTSCONTROLLER_CONNECTIONSURL
            value: "http://192.168.99.100:30494/connections/"
          - name: CONNECTIONPOSTSCONTROLLER_USERSURL
            value: "http://192.168.99.100:30494/users/"
          - name: REDIS_HOSTNAME
            value: "192.168.99.100"
          - name: REDIS_PORT
            value: "32410"