kind: Service
apiVersion: v1
metadata:
  name: stateless
spec:
  selector:
    app: cn-stateless
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cn-stateless
  labels:
    app: cn-stateless
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cn-stateless
  template:
    metadata:
      labels:
        app: cn-stateless
    spec:
      containers:
      - name: cn-stateless
        image: cdavisafc/cloudnative-statelessness
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"datasource":{"url":"jdbc:mysql://192.168.99.100:32321/cookbook"}}}'